apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-datadeling
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
  replicas:
    min: 1
    max: 1
  ingresses:
    - {{ ingress.url }}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: tiltakspenger-vedtak
        - application: tiltakspenger-arena
          namespace: tpts
          cluster: {{ cluster-fss }}
